'use client';

import { Circle } from 'lucide-react';
import type { Project, TaskStatus } from '../model/workspace-types';

export type SpaceView = 'Overview' | 'Board' | 'List' | 'Calendar' | 'Gantt' | 'Table';
const statuses: TaskStatus[] = ['Backlog', 'In progress', 'Done'];

export function SpaceTabContent({ view, projects, onOpenProject }: { view: Exclude<SpaceView, 'Overview'>; projects: Project[]; onOpenProject: (id: string) => void }) {
  const entries = projects.flatMap((project) => project.tasks.map((task) => ({ project, task })));
  if (view === 'Board') return <section className="p-4"><h2 className="sr-only">Space Board</h2><div className="flex min-h-[560px] gap-4 overflow-x-auto">{statuses.map((status) => <article key={status} className="w-72 shrink-0 rounded-xl bg-slate-100/80 p-3 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="rounded-full bg-white px-2 py-1 text-xs font-semibold dark:bg-slate-950">{status}</span><span className="text-xs text-slate-500">{entries.filter((entry) => entry.task.status === status).length}</span></div><div className="mt-3 space-y-3">{entries.filter((entry) => entry.task.status === status).map(({ project, task }) => <button type="button" key={task.id} onClick={() => onOpenProject(project.id)} className="block w-full rounded-lg border border-slate-200 bg-white p-3 text-left shadow-sm hover:border-indigo-300 dark:border-slate-800 dark:bg-slate-950"><p className="text-sm font-semibold">{task.title}</p><p className="mt-2 text-xs text-slate-500">{project.name} · {task.assignee}</p></button>)}</div></article>)}</div></section>;
  if (view === 'List' || view === 'Table') return <section className="p-4"><h2 className="sr-only">{view === 'List' ? 'Space List' : 'Space Table'}</h2><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-[minmax(260px,1fr)_180px_160px_140px] gap-4 border-b border-slate-200 bg-slate-50 px-4 py-3 text-xs font-semibold text-slate-500 dark:border-slate-800 dark:bg-slate-900"><span>Task</span><span>Project</span><span>Status</span><span>Due date</span></div>{entries.map(({ project, task }) => <button type="button" onClick={() => onOpenProject(project.id)} key={task.id} className="grid w-full grid-cols-[minmax(260px,1fr)_180px_160px_140px] gap-4 border-b border-slate-100 px-4 py-3 text-left text-sm hover:bg-indigo-50/70 dark:border-slate-900 dark:hover:bg-indigo-950/20"><span className="font-semibold">{task.title}</span><span className="text-slate-500">{project.name}</span><span className="inline-flex items-center gap-1"><Circle size={10} className={task.status === 'Done' ? 'fill-emerald-500 text-emerald-500' : task.status === 'In progress' ? 'fill-blue-500 text-blue-500' : 'text-slate-400'} />{task.status}</span><span className="text-slate-500">{task.dueDate || '—'}</span></button>)}</div></section>;
  if (view === 'Calendar') return <section className="p-4"><h2 className="sr-only">Space Calendar</h2><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="grid grid-cols-7 border-b border-slate-200 text-center text-xs font-semibold text-slate-500 dark:border-slate-800">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span className="p-3" key={day}>{day}</span>)}</div><div className="grid grid-cols-7">{Array.from({ length: 28 }, (_, index) => { const day = index + 1; const items = entries.filter(({ task }) => Number(task.dueDate.slice(-2)) === day); return <div className="min-h-28 border-b border-r border-slate-100 p-2 dark:border-slate-900" key={day}><span className="text-xs text-slate-400">{day}</span>{items.map(({ project, task }) => <button onClick={() => onOpenProject(project.id)} key={task.id} className="mt-2 block w-full truncate rounded bg-indigo-100 px-2 py-1 text-left text-xs text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{task.title}</button>)}</div>; })}</div></div></section>;
  return <section className="p-4"><h2 className="sr-only">Space Gantt</h2><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="grid min-w-[900px] grid-cols-[280px_repeat(7,minmax(0,1fr))] text-xs"><div className="border-b border-r border-slate-200 p-3 font-semibold dark:border-slate-800">Project task</div>{['15', '16', '17', '18', '19', '20', '21'].map((day) => <div key={day} className="border-b border-r border-slate-200 p-3 text-center text-slate-500 dark:border-slate-800">Jul {day}</div>)}{entries.map(({ project, task }, index) => <div className="contents" key={task.id}><button onClick={() => onOpenProject(project.id)} className="border-b border-r border-slate-100 p-4 text-left font-semibold hover:text-indigo-600 dark:border-slate-900">{task.title}<span className="mt-1 block text-xs font-normal text-slate-500">{project.name}</span></button>{Array.from({ length: 7 }, (_, day) => <div className="relative border-b border-r border-slate-100 p-4 dark:border-slate-900" key={day}>{day === index + 1 && <span className="absolute inset-y-3 left-1 right-[-110%] rounded-full bg-indigo-500" />}</div>)}</div>)}</div></div></section>;
}